title: "Fabian Kossmann KI und Data Science"
title_en: "Fabian Kossmann AI and Data Science"
email: fabiankossmann98@gmail.com
url: "https://fabian-kossmann.de"
baseurl: ""
timezone: Europe/Berlin

collections:
  cv:
    output: false
